version: '3.8'

services:
  crud_app:
    container_name: crud_app
    image: "crud_app:latest"
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - ${DB_HOST}

  postgres_db:
    image: postgres:13
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
