-- Usuários e permissões

CREATE USER admin WITH PASSWORD 'admin_admin'; 
GRANT ALL PRIVILEGES ON DATABASE restaurante_db TO admin; 
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin; 
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin; 

CREATE USER gerente WITH PASSWORD 'senha_gerente'; 
GRANT SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gerente; 
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gerente; 

CREATE USER funcionario WITH PASSWORD 'senha_funcionario'; 
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA public TO funcionario; 
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO funcionario; 
